##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh
# location of code, the full url to your github repository
source-code: https://github.com/ghiblitan/redcliff.git

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Red Cliff Paintings
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A collection of paintings from Song to Yuan featuring Su Shi's prose-poem Red Cliff
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: This collection features five painting by different artists from Song to Yuan Dynasty depicting Su Shi’s prose-poem, Red Cliff (赤壁赋). Written after Su was being exiled to Huangzhou, the poem portrayed Su and his companions travelling on a small boat to visit the site that was assumed to be the Red Cliffs just outside Huangzhou on an autumn night in 1082, as they were recalling the Battle of Red Cliff(赤壁之战) in the Three Kingdom Period(208 AD). Su reflected on the rise and fall of the heroic figures such as Liu Bei, Sun Quan and Cao Cao and the transience nature of life in relation to his own personal encounter. Understanding the historical and the biographical contexts, the featuring artists in this collection take advantage of the pictorial language of Su’s prose-poem and visually interpreted it into different formats and styles that address both the narrative and the poetic aspects of the poem.

# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Ghibli Tan

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection)
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: Virtual_Exhibition_Red_Cliff

##########
# Site/Organization Branding
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id:

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true

##########
# BUILD SETTINGS
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
